version: "3"

services:
  wordpress: # Service WordPress
    image: liticia659/wordpressdockfile:1.0 # Utiliser l'image personnalisée de WordPress
    networks:
      - frontend_network # Connecter au réseau frontend
      - backend_network # Connecter au réseau backend
    ports:
      - "80:80" # Mapper le port 80 du conteneur WordPress au port 80
    volumes:
      - /mnt/c/Users/hp/Desktop/projetDocker/frontend:/var/www/html # Monter le répertoire local sur le répertoire WordPress
    depends_on:
      - mariadb # Attendre que le service MariaDB soit prêt avant de démarrer WordPress
    environment:
      - WORDPRESS_DB_HOST=mariadb # Hôte de la base de données MariaDB
      - WORDPRESS_DB_NAME=my_wp_db # Nom de la base de données pour WordPress
      - WORDPRESS_DB_USER=my_wp_user # Nom d'utilisateur pour la base de données WordPress
      - WORDPRESS_DB_PASSWORD=my_wp_password # Mot de passe pour l'utilisateur de la base de données WordPress

  mariadb: # Service MariaDB
    image: liticia659/mariadbdockfile:1.0 # Utiliser l'image personnalisée de MariaDB
    networks:
      - backend_network # Connecter au réseau backend
    volumes:
      - ./path/to/mysql-data:/var/lib/mysql # Monter le volume pour les données de la base de données
      - /mnt/c/Users/hp/Desktop/projetDocker/my.cnf:/etc/mysql/my.cnf # Monter le fichier de configuration my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=my_root_password # Mot de passe root de la base de données MariaDB
      - MYSQL_DATABASE=my_wp_db # Nom de la base de données pour WordPress
      - MYSQL_USER=my_wp_user # Nom d'utilisateur pour la base de données WordPress
      - MYSQL_PASSWORD=my_wp_password # Mot de passe pour l'utilisateur de la base de données WordPress

networks:
  frontend_network:
    driver: bridge # Utiliser le pilote bridge pour le réseau frontend
  backend_network:
    driver: bridge # Utiliser le pilote bridge pour le réseau backend
